name: Release image + Helm chart K8s Operator
on:
  push:
    tags:
      - "infisical-k8-operator/v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF_NAME#infisical-k8-operator/}"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install python
        uses: actions/setup-python@v4
        
      - name: Generate Helm Chart
        run: sh k8-operator/scripts/generate-helm.sh
        
      - name: Update Helm Chart Version
        run: sh k8-operator/scripts/update-version.sh ${{ steps.extract_version.outputs.version }}

      - name: 🔧 Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🐋 Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: k8-operator
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            infisical/kubernetes-operator:latest
            infisical/kubernetes-operator:${{ steps.extract_version.outputs.version }}
            
      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli      

      - name: Build and push helm package to Cloudsmith
        run: cd helm-charts && sh upload-k8s-operator-cloudsmith.sh
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
            
      - name: Commit and Push Helm Changes
        run: |
          git add .
          git commit -m "Update Helm chart to version ${{ steps.extract_version.outputs.version }}" || echo "No changes to commit"
          git push